---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: NJlmA5m+wQZLHPFn/yejnsBYu+iRWFRDlMpvbKxiWA4=
  REDIS_TLS_URL: rediss://:pf3e7de84cb282cf1e21fb170abc557d493769a9466977d81c69c92752b03e0a9@ec2-54-209-47-44.compute-1.amazonaws.com:18780
  GOOGLE_CREDENTIALS_CLIENT_ID: 27551357076-kuoiutppet00rtmg3fvck2aiq7iqtaui.apps.googleusercontent.com
  GOOGLE_CREDENTIALS_CLIENT_SECRET: DXaTrUwv-Lb3RMd0KlF6OXtr

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  MSG_KEY: 88EpejsFWNjm2d36hCUs5jo5wN57fgf1z1OdW/t2s/M=
  SESSION_SECRET: some_secret

production:
  API_URL: https://calendar-coordinator-api.herokuapp.com/api/v1
  APP_URL: https://calendar-coordinator-web.herokuapp.com
  SESSION_SECRET: some_secret
  MSG_KEY: Lw0LB8E4UJ6bBvzwR9VHpasc+y/TYjpjPuM43jkjtV4=
