---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret

production:
  API_URL: https://calendar-coordinator-api.herokuapp.com/api/v1
  APP_URL: https://calendar-coordinator-web.herokuapp.com
  SESSION_SECRET: some_secret
